version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ngcash
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

  ngcash-api:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.development
    container_name: ngcash-api
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres-data:
  pgadmin-data:
